[cranelift_coverage]
features = "cranelift,singlepass,llvm,test-no-traps,test-cranelift"
examples = ["early-exit", "engine-jit", "engine-native", "engine-headless", "cross-compilation", "compiler-cranelift", "exported-function", "wasi"]
release = true

[llvm_coverage]
features = "cranelift,singlepass,llvm,test-no-traps,test-llvm"
examples = ["compiler-llvm"]
release = true

[singlepass_coverage]
features = "cranelift,singlepass,llvm,test-no-traps,test-singlepass"
examples = ["compiler-singlepass"]
release = true

[report]
out = ["Xml"]