# This template installs pkg-config (if doesn't exist in the systems)

steps:
  - bash: |
      set -ex
      if [ -x "`command -v pkg-config`" ]; then
        echo `command -v pkg-config` `pkg-config --version` installed
      else
        brew install pkg-config
      fi
    displayName: "Install pkg-config (macOS)"
    condition: eq(variables['Agent.OS'], 'Darwin')

  - bash: |
      set -ex
      if [ -x "`command -v pkg-config`" ]; then
        echo `command -v pkg-config` `pkg-config --version` installed
      else
        curl -O https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
        tar xzf pkg-config-0.29.2.tar.gz
        cd pkg-config-0.29.2
        ./configure
        make install
      fi
    displayName: "Install pkg-config (Linux)"
    condition: eq(variables['Agent.OS'], 'Linux')

  - bash: |
      set -ex
      pkg-config --version
    displayName: Pkg-config version
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))
